<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ZYC.VerbClass.Academic.Domain.Shared\ZYC.VerbClass.Academic.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" />
    <PackageReference Include="Volo.Abp.MultiTenancy.Abstractions" />
    <PackageReference Include="Volo.Abp.SettingManagement.Domain" />
  </ItemGroup>

</Project>
