<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ZYC.VerbClass.Academic.Domain\ZYC.VerbClass.Academic.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Volo.Abp.Identity.Domain" />
  </ItemGroup>

</Project>
