<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ZYC.VerbClass.Academic.Application\ZYC.VerbClass.Academic.Application.csproj" />
    <ProjectReference Include="..\ZYC.VerbClass.Domain\ZYC.VerbClass.Domain.csproj" />
    <ProjectReference Include="..\ZYC.VerbClass.Application.Contracts\ZYC.VerbClass.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" />
    <PackageReference Include="Volo.Abp.Account.Application" />
    <PackageReference Include="Volo.Abp.Identity.Application" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" />
  </ItemGroup>

</Project>
